= Docker
:toc: macro

toc::[]


== Style

These styling rules are not strict but what I personally use
to keep dockerfiles readable, grep-able, and git friendly.

=== Trailing noop command

Use bash's `:` command to end compound `RUN` statements in
dockerfiles. An ending `:` command allows for inserting
new statements without generating a merge conflict (due
to the required newline escape).

The `:` bash built-in is a noop command equivalent to the
`true` command.

.Example usage
[source,dockerfile]
----
RUN : \
    && command1 \
    && command2 \
    && :
----

.Adding a new line before the the trailing `:`
[source,dockerfile]
----
RUN : \
    && command1 \
    && command2 \
    && inserted-command \
    :
----

References:

* https://youtu.be/BdxdRlTnPEE[anthony explains: dockerfile RUN : \ && syntax]

=== Single line statements

Each command should be on its own line. Long commands can be broken
up into multiple lines with additional indentation.
Commands that list packages should have each package
on its own line and alphabetized.

[source,dockerfile]
----
RUN : \
	&& command1 \
	&& download-pkgs \
		abc-pkg \
		hello-world \
		howdy-texas \
	&& long-command-with-many-flags \
		--flag1 \
		--flag2 \
		--flagN \
	&& comand-with-pipe | \
		second-command --process | \
		final-command \
	&& :
----
